export const GET_TIKET_FILTER = 'GET_TIKET_FILTER';
export const GET_SIDE_FILTER = 'GET_SIDE_FILTER';
export const TIKETS_LOAD = 'TIKETS_LOAD';
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';
export const GET_TIKET = 'GET_TIKET';
